name: "Cypress"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "cypress"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Cypress.io
      uses: cypress-io/github-action@v4.2.0
      with: 
        start: npm start
